# Generated by Django 3.2.5 on 2021-07-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Jardineria',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID')),
                ('maceteros', models.IntegerField(verbose_name='Maceteros')),
                ('tierradehojas', models.IntegerField(verbose_name='Tierra de hojas')),
                ('flores', models.IntegerField(verbose_name='Flores')),
                ('arbustos', models.IntegerField(verbose_name='Arbustos')),
            ],
        ),
    ]
