# Generated by Django 3.2.5 on 2021-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maceteros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flores', models.IntegerField(verbose_name='Flores')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Jardineria',
        ),
    ]
