# Generated by Django 3.2.5 on 2021-07-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210721_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tierradehojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tierradehojas', models.IntegerField(verbose_name='Tierra de hojas')),
            ],
        ),
        migrations.CreateModel(
            name='Arbustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbustos', models.IntegerField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
